### ISSUE TITLE
Potential .install phpcs fixes

### ISSUE THREAD

**Issue by nielsonm** [cybtachyon/openshift_api#7]
Indentation on ternary assignment is triggering a phpcs failure on the following lines.

https://github.com/cybtachyon/openshift_api/blob/e5b1720f7a0054e969e9ac6d2ca5a806fd38e976/openshift_api.install#L49

https://github.com/cybtachyon/openshift_api/blob/e5b1720f7a0054e969e9ac6d2ca5a806fd38e976/openshift_api.install#L50

Removing the extra spacing lowers readability, but there should be a way to pass coding standards & not make it hard to read.

**Comment by cybtachyon** [comment]
Resolved, thanks!
